server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: extintor-service
          uri: lb://extintor-service
          predicates:
            - Path=/extintor/**
        - id: inspecao-service
          uri: lb://inspecao-service
          predicates:
            - Path=/inspecao/**
        - id: historico-service
          uri: lb://historico-service
          predicates:
            - Path=/historico/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: "*"